if(NOT PROJECT_ROOT_DIR)
    set(PROJECT_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
endif()

set(NLOHMANN_INCLUDE_DIR "${PROJECT_ROOT_DIR}/third_party")

set(EIGEN_INCLUDE_DIR "")
if(EXISTS "${PROJECT_ROOT_DIR}/third_party/eigen")
    set(EIGEN_INCLUDE_DIR "${PROJECT_ROOT_DIR}/third_party/eigen")
elseif(EXISTS "/opt/homebrew/include/eigen3")
    set(EIGEN_INCLUDE_DIR "/opt/homebrew/include/eigen3")
elseif(EXISTS "/usr/local/include/eigen3")
    set(EIGEN_INCLUDE_DIR "/usr/local/include/eigen3")
elseif(EXISTS "/usr/include/eigen3")
    set(EIGEN_INCLUDE_DIR "/usr/include/eigen3")
elseif(EXISTS "${PROJECT_ROOT_DIR}/../shared_libs/eigen")
    set(EIGEN_INCLUDE_DIR "${PROJECT_ROOT_DIR}/../shared_libs/eigen")
endif()

set(FFTW_INCLUDE_DIR "")
set(FFTW_LIBRARY_DIR "")
if(EXISTS "${PROJECT_ROOT_DIR}/third_party/fftw-install")
    set(FFTW_INCLUDE_DIR "${PROJECT_ROOT_DIR}/third_party/fftw-install/include")
    set(FFTW_LIBRARY_DIR "${PROJECT_ROOT_DIR}/third_party/fftw-install/lib")
elseif(EXISTS "/opt/homebrew/Cellar/fftw")
    file(GLOB FFTW_VERSIONS "/opt/homebrew/Cellar/fftw/*")
    list(SORT FFTW_VERSIONS)
    list(REVERSE FFTW_VERSIONS)
    list(GET FFTW_VERSIONS 0 FFTW_LATEST)
    set(FFTW_INCLUDE_DIR "${FFTW_LATEST}/include")
    set(FFTW_LIBRARY_DIR "${FFTW_LATEST}/lib")
elseif(EXISTS "/usr/local/include/fftw3.h")
    set(FFTW_INCLUDE_DIR "/usr/local/include")
    set(FFTW_LIBRARY_DIR "/usr/local/lib")
elseif(EXISTS "/usr/include/fftw3.h")
    set(FFTW_INCLUDE_DIR "/usr/include")
    set(FFTW_LIBRARY_DIR "/usr/lib/x86_64-linux-gnu")
elseif(WIN32)
    find_package(FFTW REQUIRED)
endif()

file(MAKE_DIRECTORY "${PROJECT_ROOT_DIR}/output")

message(STATUS "=== 库路径检测 (root: ${PROJECT_ROOT_DIR}) ===")
message(STATUS "Eigen: ${EIGEN_INCLUDE_DIR}")
message(STATUS "FFTW Include: ${FFTW_INCLUDE_DIR}")
message(STATUS "FFTW Library: ${FFTW_LIBRARY_DIR}")
message(STATUS "nlohmann: ${NLOHMANN_INCLUDE_DIR}")
